# Draft PR Review Generation
# Only generates reviews for draft pull requests

name: Review Draft PRs
on:
  pull_request:
    types: [opened, converted_to_draft]

jobs:
  review:
    # Only run for draft PRs
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate PR Review
        uses: augmentcode/review-pr@v0
        with:
          augment_session_auth: ${{ secrets.AUGMENT_SESSION_AUTH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ github.event.pull_request.number }}
          repo_name: ${{ github.repository }}
